production:
  adapter:  postgresql
  database: <%= ENV["CARTOQUE_DATABASE"] || "cartoque" %>
  username: <%= ENV["CARTOQUE_USERNAME"] || "cartoque" %>
  password: <%= ENV["CARTOQUE_PASSWORD"] || "" %>
  host:     <%= ENV["CARTOQUE_HOST"]     || "localhost" %>
  port:     <%= ENV["CARTOQUE_PORT"]     || 5432 %>
  encoding: utf8
  pool:     10
  #timeout: 5000
development:
  adapter:  postgresql
  database: <%= ENV["CARTOQUE_DATABASE"] || "cartoque" %>
  username: <%= ENV["CARTOQUE_USERNAME"] || "cartoque" %>
  password: <%= ENV["CARTOQUE_PASSWORD"] || "" %>
  host:     <%= ENV["CARTOQUE_HOST"]     || "localhost" %>
  port:     <%= ENV["CARTOQUE_PORT"]     || 5432 %>
  encoding: utf8
  pool:     10
  #timeout: 5000
test:
  adapter:  postgresql
  database: cartoque_test
  username: postgres
  encoding: utf8
  pool:     10
